// <auto-generated />
using System;
using EmreWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmreWebApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201221144053_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmreWebApi.Models.Bok", b =>
                {
                    b.Property<int>("Bok_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Betyg")
                        .HasColumnType("int");

                    b.Property<string>("BokTitel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Författare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Isbn")
                        .HasColumnType("int");

                    b.Property<int?>("UtgivningsÅr")
                        .HasColumnType("int");

                    b.HasKey("Bok_Id");

                    b.ToTable("Böcker");
                });

            modelBuilder.Entity("EmreWebApi.Models.Boklån", b =>
                {
                    b.Property<int>("Boklån_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BokId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LåneDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("LåntagareId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturDatum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Utlånad")
                        .HasColumnType("bit");

                    b.HasKey("Boklån_Id");

                    b.ToTable("Boklån");
                });

            modelBuilder.Entity("EmreWebApi.Models.Låntagare", b =>
                {
                    b.Property<int>("Lånekort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Förnamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Lånekort");

                    b.ToTable("Låntagare");
                });
#pragma warning restore 612, 618
        }
    }
}
